FROM python:3.10-slim

WORKDIR /app

COPY requirements-scraper.txt .
RUN pip install --no-cache-dir -r requirements-scraper.txt

COPY src /app/src

RUN mkdir -p /app/logs && chmod 777 /app/logs
ENV PYTHONPATH=/app/src:$PYTHONPATH

CMD ["python", "-u", "/app/src/ingestion/connectors/yahoo_connector.py"]