FROM python:3.10-slim

WORKDIR /app

# Copy the src directory and its contents
COPY src /app/src

# Create logs directory
RUN mkdir -p /app/logs && chmod 777 /app/logs

# Install required packages
RUN pip install requests kafka-python yfinance defeatbeta-api stockdex dotenv

# Set Python path to recognize modules
ENV PYTHONPATH=/app/src:$PYTHONPATH

# Update CMD to use correct path
CMD ["python", "-u", "/app/src/ingestion/connectors/yahoo_connector.py"]